apiVersion : apps/v1
kind: Deployment
metadata:
  name: "restkub01-9e41"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "restkub01-9e41"
  template:
    metadata:
      labels:
        app: "restkub01-9e41"
    spec:
      containers:
        - name: "restkub01-9e41"
          image: "restcn01.azurecr.io/restkub01"
          ports:
          - containerPort: 80