apiVersion: v1
kind: Service
metadata:
    name: "restkub01-9e41"
    labels:
        app: "restkub01-9e41"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "restkub01-9e41"