on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: restcn01.azurecr.io
        username: ${{ secrets.acr_restcn01_username }}
        password: ${{ secrets.acr_restcn01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t restcn01.azurecr.io/restkub01:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push restcn01.azurecr.io/restkub01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_restkub01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rest-kub-01a2b0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rest-kub-01a2b0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rest-kub-01a2b0
        container-registry-url: restcn01.azurecr.io
        container-registry-username: ${{ secrets.acr_restcn01_username }}
        container-registry-password: ${{ secrets.acr_restcn01_password }}
        secret-name: restkub01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rest-kub-01a2b0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          restcn01.azurecr.io/restkub01:${{ github.sha }}
        imagepullsecrets: |
          restkub01dockerauth
